name: build

permissions: read-all

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, '3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      env:
        KEY_MODELLER: ${{ secrets.KEY_MODELLER }}
      run: |
        tools/install_deps.sh ~/deps ${{ matrix.python-version }}
    - name: Test
      run: |
        export PATH=~/deps/bin:$PATH
        eval "$(conda shell.bash hook)"
        conda activate python${{ matrix.python-version }}
        make
        pytest --cov=. --cov-branch --cov-report=xml -v .
        flake8 --ignore=E402,W503,W504 --exclude=doc/conf.py
    - uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
