name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [2.7, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      env:
        KEY_MODELLER: ${{ secrets.KEY_MODELLER }}
      run: |
        tools/install_deps.h ~/deps ~/miniconda ${{ matrix.python-version }}
    - name: Test
      run: |
        export PATH=~/deps/bin:$PATH
        source ~/miniconda/bin/activate python${{ matrix.python-version }}
        make
        nosetests --with-coverage --cover-branches
    - name: Upload coverage to codecov
      run: |
        bash <(curl -s https://codecov.io/bash)
